Grep for extra errors in unit test log file.
Some errors are not caught by the Automake test driver because Cutter
won't throw a proper error. Specifically, when trying to use an
undefined symbol as a result of forgetting to linked against some
object or forgetting to provide an implementation, Cutter will only
show a warning (!), but otherwise carry on with the next test and will
not error out. What a horrible, horrible idea...

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -23,4 +23,10 @@ test_urlfifo_la_CFLAGS = $(AM_CFLAGS)
 CLEANFILES = test_report.xml test_report_junit.xml
 
 EXTRA_DIST = cutter2junit.xslt
+
+check-local: check-TESTS
+	@if $(GREP) -w cutter $(TEST_LOGS); then \
+	    echo "Unit tests failed (check log)"; \
+	    exit 1; \
+	fi
 endif
